# Generated by Django 4.2.27 on 2026-01-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_agent_owner_agentclaim"),
    ]

    operations = [
        migrations.RemoveField(model_name="agentclaim", name="claimed_by",),
        migrations.RemoveField(model_name="profile", name="agent_owner",),
        migrations.AddField(
            model_name="agentclaim",
            name="owner_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="agentclaim",
            name="proof_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
