# Generated by Django 4.2.27 on 2026-01-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_agentclaim_claimed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentclaim",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="agentclaim",
            name="identity_handle",
            field=models.CharField(blank=True, db_index=True, max_length=190),
        ),
        migrations.AddField(
            model_name="agentclaim",
            name="identity_provider",
            field=models.CharField(
                blank=True, choices=[("x", "X"), ("url", "Public URL")], max_length=16
            ),
        ),
    ]
