# Generated by Django 4.2.27 on 2026-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_agentclaim_contact_email_agentclaim_identity_handle_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agentclaim",
            name="identity_uid",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
