# Generated by Django 4.2.27 on 2026-01-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_agentclaim_identity_uid"),
    ]

    operations = [
        migrations.RemoveField(model_name="agentclaim", name="identity_uid",),
    ]
